part of dartcord;

class Events {
  static const hello = 'hello';
  static const ready = 'ready';
  static const resumed = 'resumed';
  static const reconnect = 'reconnect';
  static const invalidSession = 'invalid_session';
  static const channelCreate = 'channel_create';
  static const channelUpdate = 'channel_update';
  static const channelDelete = 'channel_delete';
  static const channelPinsUpdate = 'channel_pins_update';
  static const guildCreate = 'guild_create';
  static const guildUpdate = 'guild_update';
  static const guildDelete = 'guild_delete';
  static const guildBanAdd = 'guild_ban_add';
  static const guildBanRemove = 'guild_ban_remove';
  static const guildEmojisUpdate = 'guild_emojis_update';
  static const guildInteractionsUpdate = 'guild_integrations_update';
  static const guildMemberAdd = 'guild_member_add';
  static const guildMemberRemove = 'guild_member_remove';
  static const guildMemberUpdate = 'guild_member_update';
  static const guildMemberChunk = 'guild_member_chunk';
  static const guildRoleCreate = 'guild_role_create';
  static const guildRoleUpdate = 'guild_role_update';
  static const guildRoleDelete = 'guild_role_delete';
  static const inviteCreate = 'invite_create';
  static const inviteDelete = 'invite_delete';
  static const messageCreate = 'message_create';
  static const messageUpdate = 'message_update';
  static const messageDelete = 'message_delete';
  static const messageDeleteBulk = 'message_delete_bulk';
  static const messageReactionAdd = 'message_reaction_add';
  static const messageReactionRemove = 'message_reaction_remove';
  static const messageReactionRemoveAll = 'message_reaction_remove_all';
  static const messageReactionRemoveEmoji = 'message_reaction_remove_emoji';
  static const presenceUpdate = 'presence_update';
  static const typingStart = 'typing_start';
  static const userUpdate = 'user_update';
  static const voiceSateUpdate = 'voice_state_update';
  static const voiceServerUpdate = 'voice_server_update';
  static const webhooksUpdate = 'webhooks_update';
}
